"""New fields added

Revision ID: 921069846a6e
Revises: a51970c2c6df
Create Date: 2024-05-27 11:02:05.221660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921069846a6e'
down_revision: Union[str, None] = 'a51970c2c6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('email', sa.String(length=40), nullable=False))
    op.add_column('reservations', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('reservations', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'created_at')
    op.drop_column('reservations', 'name')
    op.drop_column('passengers', 'email')
    # ### end Alembic commands ###
