"""email unique

Revision ID: bad3a5f18f02
Revises: 921069846a6e
Create Date: 2024-05-27 12:18:40.869887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad3a5f18f02'
down_revision: Union[str, None] = '921069846a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'passengers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passengers', type_='unique')
    # ### end Alembic commands ###
